Try-Catch And Throw

JS는 에러가 발생하면 스크립트는 중단되고 콜솔에 에러가 출력된다.
일반적인 에러 출력보다 생성자 에러를 생성하려면 => try-catch

try => 코드실행, 코드 실행에 에러가 없다면 catch는 건너뛴다.
catch => try로 넘어간다.

